---
- name: httpd install
  hosts: all
  become: true
  tasks:
    - name: httpd
      yum:
        name: httpd
        state: absent
    
    - name: httpd
      yum:
        name: httpd
        state: present
    
    - name: firewall
      service:
        state: stopped
        enabled: false
        
    - name: httpd install
      service:
        state: started
        enabled: true
